export interface LeadInterface {
         _id?: string,
         firstName: string,
         lastName: string, 
         email: string,
         fatherName?: string,
         spouseName?: string,
         dateOfBirth?: any,
         gender?: string,
         phone?: string,
         address?: string,
         photo: string,
         country?: string,
         passportavailableyn?: string,
         passportnumber?: string,
         passportissueddate?: string,
         passportexpirydate?: string,
         visarejected?: string,
         visarejectednotes?: string,
         alternatephone?: string,
}